# Generated by Django 5.1.3 on 2025-04-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetter', '0002_educationitem_experienceitem_projectitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienceitem',
            name='achivments',
        ),
        migrations.AddField(
            model_name='experienceitem',
            name='achivements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationitem',
            name='course',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='educationitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='experienceitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experienceitem',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experienceitem',
            name='timelaps',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
