# Generated by Django 5.1.3 on 2025-04-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetter', '0003_remove_experienceitem_achivments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationitem',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
