# Generated by Django 5.1.3 on 2025-04-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetter', '0004_alter_educationitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
